services:
  web:
    build:
      context: .
      dockerfile: docker/go/Dockerfile.prod
    image: gin-web-admin
    restart: on-failure
    ports:
      - '8081:8081'
    volumes:
      - .:/code
    environment:
      - RUN_MODE=release  #debug or release
      # - GIN_MODE=release
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "2G"
    working_dir: /code
