name: Go
on:
  push:
    branches:
    - dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: Build
        run: go build -v .
