name: Go

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build:
    name: Test & Lint
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          go-version-file: 'go.mod'
          check-latest: true
      - name: Go Test
        run: go test ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11
